import { Point3D, CameraPose } from "../types/slam";

/**
 * Exports 3D point cloud in Stanford PLY format (ASCII).
 * Compatible with Blender, MeshLab, CloudCompare, Meshroom.
 */
export function exportToPLY(points: Point3D[], filename = "lingbot_map.ply"): void {
  if (points.length === 0) {
    alert("No hay puntos 3D para exportar");
    return;
  }

  const header = [
    "ply",
    "format ascii 1.0",
    "comment Generated by LingBot-Map 3D Live Reconstruction",
    `element vertex ${points.length}`,
    "property float x",
    "property float y",
    "property float z",
    "property uchar red",
    "property uchar green",
    "property uchar blue",
    "property float confidence",
    "end_header",
  ].join("\n");

  const rows: string[] = [];
  for (let i = 0; i < points.length; i++) {
    const p = points[i];
    const conf = p.confidence ?? 0.9;
    rows.push(
      `${p.x.toFixed(4)} ${p.y.toFixed(4)} ${p.z.toFixed(4)} ${Math.round(p.r)} ${Math.round(p.g)} ${Math.round(p.b)} ${conf.toFixed(2)}`
    );
  }

  const blob = new Blob([header + "\n" + rows.join("\n")], { type: "text/plain" });
  downloadBlob(blob, filename);
}

/**
 * Exports 3D Point Cloud as an OBJ file with vertex colors (Wavefront OBJ extension)
 */
export function exportToOBJ(points: Point3D[], filename = "lingbot_map.obj"): void {
  if (points.length === 0) {
    alert("No hay puntos para exportar");
    return;
  }

  const lines = [
    "# LingBot-Map 3D Wavefront OBJ Export",
    `# Total vertices: ${points.length}`,
  ];

  for (let i = 0; i < points.length; i++) {
    const p = points[i];
    // Wavefront OBJ vertex color convention: v x y z r g b (r,g,b in [0,1])
    const r = (p.r / 255).toFixed(4);
    const g = (p.g / 255).toFixed(4);
    const b = (p.b / 255).toFixed(4);
    lines.push(`v ${p.x.toFixed(4)} ${p.y.toFixed(4)} ${p.z.toFixed(4)} ${r} ${g} ${b}`);
  }

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  downloadBlob(blob, filename);
}

/**
 * Exports camera trajectory poses in TUM benchmark format:
 * timestamp tx ty tz qx qy qz qw
 */
export function exportTrajectoryTUM(trajectory: CameraPose[], filename = "trajectory_tum.txt"): void {
  if (trajectory.length === 0) {
    alert("No hay trayectoria registrada");
    return;
  }

  const lines = ["# timestamp tx ty tz qx qy qz qw"];
  for (const pose of trajectory) {
    const t = (pose.timestamp / 1000).toFixed(4);
    const p = pose.position;
    const r = pose.rotation;
    lines.push(
      `${t} ${p.x.toFixed(4)} ${p.y.toFixed(4)} ${p.z.toFixed(4)} ${r.x.toFixed(4)} ${r.y.toFixed(4)} ${r.z.toFixed(4)} ${r.w.toFixed(4)}`
    );
  }

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  downloadBlob(blob, filename);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
